export const Data = [
  {
    id: "1",
    title: "1 Apa Itu Uang",
    drive: "https://youtu.be/AJRewQtjR4g",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/1-Apa-Itu-Uang",
    category: "Crypto Blockchain",
  },
  {
    id: "2",
    title: "2 Kriptografi dan Hash Function",
    drive: "https://youtu.be/l9KFeKIajPQ",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/2-Kriptografi-dan-Hash-Function",
    category: "Crypto Blockchain",
  },
  {
    id: "3",
    title: "3 Byzantine Generals Problem",
    drive: "https://youtu.be/iGPSvArV0rU",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/3-Byzantine-Generals-Problem",
    category: "Crypto Blockchain",
  },
  {
    id: "4",
    title: "4 The Basics of Bitcoin and Blockchain",
    drive: "https://youtu.be/G8VUdWnQ34Q",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/4-The-Basics-of-Bitcoin-and-Blockchain",
    category: "Crypto Blockchain",
  },
  {
    id: "5",
    title: "5 Mining Concepts",
    drive: "https://youtu.be/-1Y8rrq-2eQ",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/5-Mining-Concepts",
    category: "Crypto Blockchain",
  },
  {
    id: "6",
    title: "6 Crypto Wallets",
    drive: "https://youtu.be/7ZFJKCo-8sg",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/6-Crypto-Wallets",
    category: "Crypto Blockchain",
  },
  {
    id: "7",
    title: "7 How to Earn Bitcoin",
    drive: "https://youtu.be/XfXGTaH_8TE",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/7-How-to-Earn-Bitcoin",
    category: "Crypto Blockchain",
  },
  {
    id: "8",
    title: "8 Bitcoin Usage",
    drive: "https://youtu.be/upDlOsbTqZU",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/8-Bitcoin-Usage",
    category: "Crypto Blockchain",
  },
  {
    id: "9",
    title: "9 Blockchain and Consensus Algorithm",
    drive: "https://youtu.be/o3hd5VovjSE",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/9-Blockchain-and-Consensus-Algorithm",
    category: "Crypto Blockchain",
  },
  {
    id: "10",
    title: "10 Blockchain Security",
    drive: "https://youtu.be/zxECdVFmYpg",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/10-Blockchain-Security",
    category: "Crypto Blockchain",
  },
  {
    id: "11",
    title: "11 Problem Pada Blockchain",
    drive: "https://youtu.be/DI5Pcprzr7M",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/11-Problem-Pada-Blockchain",
    category: "Crypto Blockchain",
  },
  {
    id: "12",
    title: "12 Privasi dan Anonimitas",
    drive: "https://youtu.be/i_znG9g6bh0",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/12-Privasi-dan-Anonimitas",
    category: "Crypto Blockchain",
  },
  {
    id: "13",
    title: "13 Perangkat Anonimitas",
    drive: "https://youtu.be/RIRdYltTMtk",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/13-Perangkat-Anonimitas",
    category: "Crypto Blockchain",
  },
  {
    id: "14",
    title: "14 Pemanfaatan Blockchain",
    drive: "https://youtu.be/o3Rj8CqX3nk",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/14-Pemanfaatan-Blockchain",
    category: "Crypto Blockchain",
  },
  {
    id: "15",
    title: "15 Teknologi Blockchain",
    drive: "https://youtu.be/xDgtPXhMOBU",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/15-Teknologi-Blockchain",
    category: "Crypto Blockchain",
  }
];