export const Data = [
  {
    id: "1",
    title: "1 Introduction to Ethereum",
    drive: "https://youtu.be/keqzHoI8g-c",
    link: "/Halaman/page/3-crypto-blockchain/8-Ethereum-Programmable-Money/1-Introduction-to-Ethereum",
    category: "Crypto Blockchain",
  },
  {
    id: "2",
    title: "2 Ethereum vs Bitcoin",
    drive: "https://youtu.be/pPCqWa4FAEA",
    link: "/Halaman/page/3-crypto-blockchain/8-Ethereum-Programmable-Money/2-Ethereum-vs-Bitcoin",
    category: "Crypto Blockchain",
  },
  {
    id: "3",
    title: "3 Ethereum History and Stages",
    drive: "https://youtu.be/MpE-0c8uOLQ",
    link: "/Halaman/page/3-crypto-blockchain/8-Ethereum-Programmable-Money/3-Ethereum-History-and-Stages",
    category: "Crypto Blockchain",
  },
  {
    id: "4",
    title: "4 Ethereum and Blockchain Components",
    drive: "https://youtu.be/eDBwFep3T7Y",
    link: "/Halaman/page/3-crypto-blockchain/8-Ethereum-Programmable-Money/4-Ethereum-and-Blockchain-Components",
    category: "Crypto Blockchain",
  },
  {
    id: "5",
    title: "5 Ethereum Denomination Wallet and Networks",
    drive: "https://youtu.be/k3D4aqJ8qMQ",
    link: "/Halaman/page/3-crypto-blockchain/8-Ethereum-Programmable-Money/5-Ethereum-Denomination-Wallet-and-Networks",
    category: "Crypto Blockchain",
  },
  {
    id: "6",
    title: "6 Introduction Ethereum transaction",
    drive: "https://youtu.be/ijAezqOEg24",
    link: "/Halaman/page/3-crypto-blockchain/8-Ethereum-Programmable-Money/6-Introduction-Ethereum-transaction",
    category: "Crypto Blockchain",
  },
  {
    id: "7",
    title: "7 the Structure of a Transaction",
    drive: "https://youtu.be/XjRAwYiJ7r8",
    link: "/Halaman/page/3-crypto-blockchain/8-Ethereum-Programmable-Money/7-the-Structure-of-a-Transaction",
    category: "Crypto Blockchain",
  },
  {
    id: "8",
    title: "8 Transaction Nonce Gas and Gas Limit",
    drive: "https://youtu.be/4gBsDZTyx6k",
    link: "/Halaman/page/3-crypto-blockchain/8-Ethereum-Programmable-Money/8-Transaction-Nonce-Gas-and-Gas-Limit",
    category: "Crypto Blockchain",
  },
  {
    id: "9",
    title: "9 the Merge",
    drive: "https://youtu.be/VsoeGSLOhzU",
    link: "/Halaman/page/3-crypto-blockchain/8-Ethereum-Programmable-Money/9-the-Merge",
    category: "Crypto Blockchain",
  },
  {
    id: "10",
    title: "10 Myths about the Merge",
    drive: "https://youtu.be/_d_jjhg4vgM",
    link: "/Halaman/page/3-crypto-blockchain/8-Ethereum-Programmable-Money/10-Myths-about-the-Merge",
    category: "Crypto Blockchain",
  },
  {
    id: "11",
    title: "11 Ethereum Virtual Machine",
    drive: "https://youtu.be/4BWxvecLwWA",
    link: "/Halaman/page/3-crypto-blockchain/8-Ethereum-Programmable-Money/11-Ethereum-Virtual-Machine",
    category: "Crypto Blockchain",
  },
  {
    id: "12",
    title: "12 Stake ETH di LIDO",
    drive: "https://youtu.be/xrXYYB6OiAA",
    link: "/Halaman/page/3-crypto-blockchain/8-Ethereum-Programmable-Money/12-Stake-ETH-di-LIDO",
    category: "Crypto Blockchain",
  },
  {
    id: "13",
    title: "13 stETH dan Withdrawal",
    drive: "https://youtu.be/1PlNP5HHQfo",
    link: "/Halaman/page/3-crypto-blockchain/8-Ethereum-Programmable-Money/13-stETH-dan-Withdrawal",
    category: "Crypto Blockchain",
  }
];