export const Data = [
  {
    id: "1",
    title: "Big Crypto Thesis",
    drive: "https://youtu.be/9Ld5hslDtlg",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/1-Big-Crypto-Thesis",
    category: "Crypto Investing",
  },
  {
    id: "2",
    title: "Bitcoin a Ponzi Scheme",
    drive: "https://youtu.be/bwOdr0WgRhM",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/2-Bitcoin-a-Ponzi-Scheme",
    category: "Crypto Investing",
  },
  {
    id: "3",
    title: "Crypto Basics",
    drive: "https://youtu.be/lR2jxNyKQsA",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/3-Crypto-Basics",
    category: "Crypto Investing",
  },
  {
    id: "4",
    title: "Mindset Crypto Gambler Mentality",
    drive: "https://youtu.be/AqiCMVZwni8",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/4-Mindset-Crypto-Gambler-Mentality",
    category: "Crypto Investing",
  },
  {
    id: "5",
    title: "Market Cycles",
    drive: "https://youtu.be/kYMsNNNXkz4",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/5-Market-Cycles",
    category: "Crypto Investing",
  },
  {
    id: "6",
    title: "Types of Cryptocurrencies",
    drive: "https://youtu.be/t0h9M7gwpvE",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/6-Types-of-Cryptocurrencies",
    category: "Crypto Investing",
  },
  {
    id: "7",
    title: "Attention Economy in Crypto",
    drive: "https://youtu.be/hZaP489yuWg",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/7-Attention-Economy-in-Crypto",
    category: "Crypto Investing",
  },
  {
    id: "8",
    title: "How to Research Crypto",
    drive: "https://youtu.be/puNFSsm1N0g",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/8-How-to-Research-Crypto",
    category: "Crypto Investing",
  },
  {
    id: "9",
    title: "Risk and Portfolio Management",
    drive: "https://youtu.be/Axdk-KxiwCo",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/9-Risk-and-Portfolio-Management",
    category: "Crypto Investing",
  },
  {
    id: "10",
    title: "NFT Fundamentals",
    drive: "https://youtu.be/axsh5xsXs7Y",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/10-NFT-Fundamentals",
    category: "Crypto Investing",
  },
  {
    id: "11",
    title: "Trade Probabilistic Thinking",
    drive: "https://youtu.be/SutJ19GMejg",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/11-Trade-Probablistic-Thinking",
    category: "Crypto Investing",
  },
  {
    id: "12",
    title: "Bitcoin and Altcoin Correlation",
    drive: "https://youtu.be/G5ESSMAVJ0k",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/12-Bitcoin-and-Altcoin-Correlation",
    category: "Crypto Investing",
  },
  {
    id: "13",
    title: "Crypto Tools",
    drive: "https://youtu.be/6Rdo0k_iKaY",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/13-Crypto-Tools",
    category: "Crypto Investing",
  },
  {
    id: "14",
    title: "Smart Money in Crypto",
    drive: "https://youtu.be/LVjApPeJyIs",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/14-Smart-Money-in-Crypto",
    category: "Crypto Investing",
  },
  {
    id: "15",
    title: "Portfolio Strategy 2023 Cheat Sheet",
    drive: "https://youtu.be/-6kfPMiMBWY",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/15-Portofolio-Strategy-2023-Cheat-Sheet",
    category: "Crypto Investing",
  },
  {
    id: "16",
    title: "Crypto Staking Strategy",
    drive: "https://youtu.be/pLBSeNhgimY",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/16-Crypto-Staking-Strategy",
    category: "Crypto Investing",
  },
  {
    id: "17",
    title: "Tutorial Exchange",
    drive: "https://youtu.be/acvKxWoaMKw",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/17-Tutorial-Exchange",
    category: "Crypto Investing",
  }
];