export const Data = [
  {
    id: "1",
    title: "1 Landscape in Blockchain Interoperability",
    drive: "https://youtu.be/Q6U_kCZuY7k",
    link: "/Halaman/page/3-crypto-blockchain/2-Blockchain-Interoperability/1-Landscape-in-Blockchain-Interoperability",
    category: "Crypto Blockchain",
  },
  {
    id: "2",
    title: "2 Blockchain Dbms",
    drive: "https://youtu.be/ebaBa9bhPdk",
    link: "/Halaman/page/3-crypto-blockchain/2-Blockchain-Interoperability/2-Blockchain-Dbms",
    category: "Crypto Blockchain",
  },
  {
    id: "3",
    title: "3 Multi Blockchain Environment",
    drive: "https://youtu.be/nmz3DIIC8OA",
    link: "/Halaman/page/3-crypto-blockchain/2-Blockchain-Interoperability/3-Multi-Blockchain-Environment",
    category: "Crypto Blockchain",
  },
  {
    id: "4",
    title: "4 Blockchain Joint",
    drive: "https://youtu.be/VSaWY8lWvwQ",
    link: "/Halaman/page/3-crypto-blockchain/2-Blockchain-Interoperability/4-Blockchain-Joint",
    category: "Crypto Blockchain",
  },
  {
    id: "5",
    title: "5 Blockchain Extension sidechain",
    drive: "https://youtu.be/tfMMZ2U0jjA",
    link: "/Halaman/page/3-crypto-blockchain/2-Blockchain-Interoperability/5-Blockchain-Extension-sidechain",
    category: "Crypto Blockchain",
  },
  {
    id: "6",
    title: "6 Decentralised Exchange",
    drive: "https://youtu.be/lWw7vm7Ahyw",
    link: "/Halaman/page/3-crypto-blockchain/2-Blockchain-Interoperability/6-Decentralised-Exchange",
    category: "Crypto Blockchain",
  },
  {
    id: "7",
    title: "7 State Pinning",
    drive: "https://youtu.be/U0EiC83pwXg",
    link: "/Halaman/page/3-crypto-blockchain/2-Blockchain-Interoperability/7-State-Pinning",
    category: "Crypto Blockchain",
  },
  {
    id: "8",
    title: "8 Consensus",
    drive: "https://youtu.be/SHCp7ptbpEs",
    link: "/Halaman/page/3-crypto-blockchain/2-Blockchain-Interoperability/8-Consensus",
    category: "Crypto Blockchain",
  },
  {
    id: "9",
    title: "9 Communication and Standardisation",
    drive: "https://youtu.be/ssXTinuTapk",
    link: "/Halaman/page/3-crypto-blockchain/2-Blockchain-Interoperability/9-Communication-and-Standardisation",
    category: "Crypto Blockchain",
  },
  {
    id: "10",
    title: "10 Bridge",
    drive: "https://youtu.be/JAANSiu5xrM",
    link: "/Halaman/page/3-crypto-blockchain/2-Blockchain-Interoperability/10-Bridge",
    category: "Crypto Blockchain",
  },
  {
    id: "11",
    title: "11 Bridge in Summary",
    drive: "https://youtu.be/JMDOUC2TwCs",
    link: "/Halaman/page/3-crypto-blockchain/2-Blockchain-Interoperability/11-Bridge-in-Summary",
    category: "Crypto Blockchain",
  },
  {
    id: "12",
    title: "12 Benefits and Drawbacks",
    drive: "https://youtu.be/-hHoUWHEuKE",
    link: "/Halaman/page/3-crypto-blockchain/2-Blockchain-Interoperability/12-Benefits-and-Drawbacks",
    category: "Crypto Blockchain",
  },
  {
    id: "13",
    title: "13 Case Study Blockchain in SCM approach",
    drive: "https://youtu.be/sDCwd2mg-Lc",
    link: "/Halaman/page/3-crypto-blockchain/2-Blockchain-Interoperability/13-Case-Study-Blockchain-in-SCM-approach",
    category: "Crypto Blockchain",
  },
  {
    id: "14",
    title: "14 Multi blockchain Multi parties",
    drive: "https://youtu.be/8-g0lflFvOo",
    link: "/Halaman/page/3-crypto-blockchain/2-Blockchain-Interoperability/14-Multi-blockchain-Multi-parties",
    category: "Crypto Blockchain",
  }
];