export const Data = [
  {
    id: "1",
    title: "1 Bitcoin Transaction In Depth",
    drive: "https://youtu.be/i1SJUPvuK38",
    link: "/Halaman/page/3-crypto-blockchain/9-Bitcoin-Transaction-in-Depth/1-Bitcoin-Transaction-In-Depth",
    category: "Crypto Blockchain",
  },
  {
    id: "2",
    title: "2 base58Check Encoding",
    drive: "https://youtu.be/LEg5X3dyOVU",
    link: "/Halaman/page/3-crypto-blockchain/9-Bitcoin-Transaction-in-Depth/2-base58Check-Encoding",
    category: "Crypto Blockchain",
  },
  {
    id: "3",
    title: "3 Bitcoin Scripting",
    drive: "https://youtu.be/6z_alDAyQM8",
    link: "/Halaman/page/3-crypto-blockchain/9-Bitcoin-Transaction-in-Depth/3-Bitcoin-Scripting",
    category: "Crypto Blockchain",
  },
  {
    id: "4",
    title: "4 Pay to Address P2A",
    drive: "https://youtu.be/PZQKI2SkA3M",
    link: "/Halaman/page/3-crypto-blockchain/9-Bitcoin-Transaction-in-Depth/4-Pay-to-Address-P2A",
    category: "Crypto Blockchain",
  },
  {
    id: "5",
    title: "5 Pay to Public Key P2PK",
    drive: "https://youtu.be/l3donT5guF8",
    link: "/Halaman/page/3-crypto-blockchain/9-Bitcoin-Transaction-in-Depth/5-Pay-to-Public-Key-P2PK",
    category: "Crypto Blockchain",
  },
  {
    id: "6",
    title: "6 Hash Locked Transaction HLT",
    drive: "https://youtu.be/E2xvBesgLUM",
    link: "/Halaman/page/3-crypto-blockchain/9-Bitcoin-Transaction-in-Depth/6-Hash-Locked-Transaction-HLT",
    category: "Crypto Blockchain",
  },
  {
    id: "7",
    title: "7 Sequence Number",
    drive: "https://youtu.be/d2GxkgfygkM",
    link: "/Halaman/page/3-crypto-blockchain/9-Bitcoin-Transaction-in-Depth/7-Sequence-Number",
    category: "Crypto Blockchain",
  },
  {
    id: "8",
    title: "8 Playing Around with IDE",
    drive: "https://youtu.be/TjohMm7ReBw",
    link: "/Halaman/page/3-crypto-blockchain/9-Bitcoin-Transaction-in-Depth/8-Playing-Around-with-IDE",
    category: "Crypto Blockchain",
  },
  {
    id: "9",
    title: "9 QUIZ",
    drive: "https://youtu.be/ujgPsjEKrmc",
    link: "/Halaman/page/3-crypto-blockchain/9-Bitcoin-Transaction-in-Depth/9-QUIZ",
    category: "Crypto Blockchain",
  },
  {
    id: "10",
    title: "10 Revisting Bitcoin Transaction",
    drive: "https://youtu.be/J11d3HZUH0o",
    link: "/Halaman/page/3-crypto-blockchain/9-Bitcoin-Transaction-in-Depth/10-Revisting-Bitcoin-Transaction",
    category: "Crypto Blockchain",
  },
  {
    id: "11",
    title: "11 RAW Transaction",
    drive: "https://youtu.be/WtGfFqOXq5g",
    link: "/Halaman/page/3-crypto-blockchain/9-Bitcoin-Transaction-in-Depth/11-RAW-Transaction",
    category: "Crypto Blockchain",
  },
  {
    id: "12",
    title: "12 Creating Bitcoin Script",
    drive: "https://youtu.be/cilQaMcK9OQ",
    link: "/Halaman/page/3-crypto-blockchain/9-Bitcoin-Transaction-in-Depth/12-Creating-Bitcoin-Script",
    category: "Crypto Blockchain",
  },
  {
    id: "13",
    title: "13 Advanced Bitcoin Protocol",
    drive: "https://youtu.be/phAdvr8RxPo",
    link: "/Halaman/page/3-crypto-blockchain/9-Bitcoin-Transaction-in-Depth/13-Advanced-Bitcoin-Protocol",
    category: "Crypto Blockchain",
  },
  {
    id: "14",
    title: "14 Bitcoin Programming with BX",
    drive: "https://youtu.be/yYerbzfObxQ",
    link: "/Halaman/page/3-crypto-blockchain/9-Bitcoin-Transaction-in-Depth/14-Bitcoin-Programming-with-BX",
    category: "Crypto Blockchain",
  },
  {
    id: "15",
    title: "15 Key Generation with BX",
    drive: "https://youtu.be/nEgrNKbVE4Q",
    link: "/Halaman/page/3-crypto-blockchain/9-Bitcoin-Transaction-in-Depth/15-Key-Generation-with-BX",
    category: "Crypto Blockchain",
  },
  {
    id: "16",
    title: "16 Other Important BX Operations",
    drive: "https://youtu.be/vszuOCLyY0w",
    link: "/Halaman/page/3-crypto-blockchain/9-Bitcoin-Transaction-in-Depth/16-Other-Important-BX-Operations",
    category: "Crypto Blockchain",
  }
];