export const Data = [
  {
    id: "1",
    title: "1 Blockchain and Security Overview",
    drive: "https://youtu.be/VmXBqm6m6OE",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/1-Blockchain-and-Security-Overview",
    category: "Crypto Blockchain",
  },
  {
    id: "2",
    title: "2 Blockchain System Components",
    drive: "https://youtu.be/XJxO8hNFeoQ",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/2-Blockchain-System-Components",
    category: "Crypto Blockchain",
  },
  {
    id: "3",
    title: "3 Blockchain Execution Environment",
    drive: "https://youtu.be/scGe9di82ec",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/3-Blockchain-Execution-Environment",
    category: "Crypto Blockchain",
  },
  {
    id: "4",
    title: "4 Blockchain is a Warzone",
    drive: "https://youtu.be/n6c7T5A-4zc",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/4-Blockchain-is-a-Warzone",
    category: "Crypto Blockchain",
  },
  {
    id: "5",
    title: "5 Instant or Unsafe Products",
    drive: "https://youtu.be/odyQNlP43ZU",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/5-Instant-or-Unsafe-Products",
    category: "Crypto Blockchain",
  },
  {
    id: "6",
    title: "6 Blockchain Security Issues",
    drive: "https://youtu.be/2NnNFPZa7-U",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/6-Blockchain-Security-Issues",
    category: "Crypto Blockchain",
  },
  {
    id: "7",
    title: "7 Cryptographic Techniques",
    drive: "https://youtu.be/8-2X2t2n9CQ",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/7-Cryptographic-Techniques",
    category: "Crypto Blockchain",
  },
  {
    id: "8",
    title: "8 Blockchain Memory Pool Mempool",
    drive: "https://youtu.be/lt_bvXkHrSY",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/8-Blockchain-Memory-Pool-Mempool",
    category: "Crypto Blockchain",
  },
  {
    id: "9",
    title: "9 Miner Extractable Value MEV",
    drive: "https://youtu.be/MOJ0sPENcgE",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/9-Miner-Extractable-Value-MEV",
    category: "Crypto Blockchain",
  },
  {
    id: "10",
    title: "10 Finality Issues",
    drive: "https://youtu.be/O6os4y-SmEc",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/10-Finality-Issues",
    category: "Crypto Blockchain",
  },
  {
    id: "11",
    title: "11 Solidity Issues",
    drive: "https://youtu.be/7KYYfQBJ2rc",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/11-Solidity-Issues",
    category: "Crypto Blockchain",
  },
  {
    id: "12",
    title: "12 Permanent Contract and Upgradeable Contract",
    drive: "https://youtu.be/Pwlvy1w_Vxg",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/12-Permanent-Contract-and-Upgradeable-Contract",
    category: "Crypto Blockchain",
  },
  {
    id: "13",
    title: "13 Decentralized Finance Issues",
    drive: "https://youtu.be/m45wQG6j60E",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/13-Decentralized-Finance-Issues",
    category: "Crypto Blockchain",
  },
  {
    id: "14",
    title: "14 User Issues",
    drive: "https://youtu.be/nZLQKELN7fw",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/14-User-Issues",
    category: "Crypto Blockchain",
  },
  {
    id: "15",
    title: "15 Security Best Practices",
    drive: "https://youtu.be/Lxl5W7myNVg",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/15-Security-Best-Practices",
    category: "Crypto Blockchain",
  }
];