export const Data = [
  {
    id: "1",
    title: "Cara Melakukan Trend Analysis",
    drive: "https://youtu.be/rNpllwGkh20",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/01-Cara-Melakukan-Trend-Analysis",
    category: "Technical Research",
  },
  {
    id: "2",
    title: "Cara Melakukan Area Analysis",
    drive: "https://youtu.be/yH8KGqwHuUk",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/02-Cara-Melakukan-Area-Analysis",
    category: "Technical Research",
  },
  {
    id: "3",
    title: "Cara Melakukan Pattern Analysis",
    drive: "https://youtu.be/oye0Xxoa1IE",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/03-Cara-Melakukan-Pattern-Analysis",
    category: "Technical Research",
  },
  {
    id: "4",
    title: "Cara Melakukan Trigger Analysis",
    drive: "https://youtu.be/xcFVbfKKZFw",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/04-Cara-Melakukan-Trigger-Analysis",
    category: "Technical Research",
  },
  {
    id: "5",
    title: "Cara Melakukan Entry Exit Analysis",
    drive: "https://youtu.be/JUf2KnMubOQ",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/05-Cara-Melakukan-Entry-Exit-Analysis",
    category: "Technical Research",
  },
  {
    id: "6",
    title: "Intro to Fundamental Research",
    drive: "https://youtu.be/9t6HvTiOIpM",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/06-Intro-to-Fundamental-Research",
    category: "Fundamental Research",
  },
  {
    id: "7",
    title: "Faktor yang Berperan Dalam Fundamental Research",
    drive: "https://youtu.be/W65I7356_aY",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/07-Faktor-yang-Berperan-Dalam-Fundamental-Research",
    category: "Fundamental Research",
  },
  {
    id: "8",
    title: "Mendalami Tokonomics Project",
    drive: "https://youtu.be/wfefQfRdZy4",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/08-Mendalami-Tokenomics-Project",
    category: "Fundamental Research",
  },
  {
    id: "9",
    title: "Intro to Narrative Analysis",
    drive: "https://youtu.be/uY-TPRI4lh8",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/09-Intro-To-Narrative-Analysis",
    category: "Narrative Analysis",
  },
  {
    id: "10",
    title: "How to be Early in Every Narratives",
    drive: "https://youtu.be/PAviyov3yPA",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/10-How-to-be-Early-in-Every-Narratives",
    category: "Narrative Analysis",
  },
  {
    id: "11",
    title: "Portofolio Allocation",
    drive: "https://youtu.be/vgB7fATJREc",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/11-Portofolio-Allocation",
    category: "Narrative Analysis",
  },
  {
    id: "12",
    title: "Possible Narratives For Next Bull Run",
    drive: "https://youtu.be/Wj84lvl-lG0",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/12-Possible-Narratives-For-Next-Bull-Run",
    category: "Narrative Analysis",
  },
  {
    id: "13",
    title: "Spatial Computing Narrative",
    drive: "https://youtu.be/24Ynm8iOpdE",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/13-Spatial-Computing-Narative",
    category: "Narrative Analysis",
  },
  {
    id: "14",
    title: "Pemahaman Dasar Mengenai Apa itu Altcoins",
    drive: "https://youtu.be/NXGVKinwP8o",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/14-Pemahaman-Dasar-Altcoins",
    category: "Altcoin Scalping",
  },
  {
    id: "15",
    title: "Pemahaman Dasar Mengenai Teknik Scalping",
    drive: "https://youtu.be/qA3zaKLGpHg",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/15-Pemahaman-Dasar-Teknik-Scalping",
    category: "Altcoin Scalping",
  },
  {
    id: "16",
    title: "Persiapan Mental Sebelum Melakukan Scalping Altcoins",
    drive: "https://youtu.be/9iIX4Am47M8",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/16-Persiapan-Mental-Sebelum-Scalping",
    category: "Altcoin Scalping",
  },
  {
    id: "17",
    title: "Persiapan Technical Sebelum Melakukan Scalping",
    drive: "https://youtu.be/6Tcpc-BaR2o",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/17-Persiapan-Teknikal-Sebelum-Scalping",
    category: "Altcoin Scalping",
  },
  {
    id: "18",
    title: "Cara Melakukan Screening Altcoins Untuk Scalping",
    drive: "https://youtu.be/ffRzQx7eVRk",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/18-Cara-Melakukan-Screening-Altcoins-untuk-Scalping",
    category: "Altcoin Scalping",
  },
  {
    id: "19",
    title: "Pengenalan Dow Theory Pada Market Crypto",
    drive: "https://youtu.be/tLsRUl0-xHM",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/19-Pengenalan-On-Chain-Trading",
    category: "On Chain Trading",
  },
  {
    id: "20",
    title: "Memahami Konsep Trend dalam Dow Theory",
    drive: "https://youtu.be/6qqHUo_DXGo",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/20-Menggali-Decentralized-Exchange",
    category: "On Chain Trading",
  },
  {
    id: "21",
    title: "Memahami Konsep Trend Lanjutan Dalam Dow Theory",
    drive: "https://youtu.be/m-fGljA37pE",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/21-Cara-Menggunakan-Wallet-dan-Exchange",
    category: "On Chain Trading",
  },
  {
    id: "22",
    title: "Penggunaan Moving Averages dan Validasi Dow",
    drive: "https://youtu.be/vEWJ54Lf1bA",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/22-Tools-untuk-On-Chain",
    category: "On Chain Trading",
  },
  {
    id: "23",
    title: "Fase pada Dow Theory",
    drive: "https://youtu.be/xy-fUVpSyIc",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/23-Kesalahan-yang-harus-dihindari-Sebelum-Transaksi-On-Chain",
    category: "On Chain Trading",
  },
];
