export const Data = [
  {
    id: "1",
    title: "1 Introduction",
    drive: "https://youtu.be/252NcN3_yYg",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/1-Introduction",
    category: "Crypto Blockchain",
  },
  {
    id: "2",
    title: "2 Sejarah Singkat Ethereum",
    drive: "https://youtu.be/4bY2MwDdfxA",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/2-Sejarah-Singkat-Ethereum",
    category: "Crypto Blockchain",
  },
  {
    id: "3",
    title: "3 Apa itu Ethereum",
    drive: "https://youtu.be/6d6issnm5oo",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/3-Apa-itu-Ethereum",
    category: "Crypto Blockchain",
  },
  {
    id: "4",
    title: "4 Berinteraksi dengan Ethereum",
    drive: "https://youtu.be/0PJvCrgWNr8",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/4-Berinteraksi-dengan-Ethereum",
    category: "Crypto Blockchain",
  },
  {
    id: "5",
    title: "5 Meta Mask Setup",
    drive: "https://youtu.be/GaIINAYdLow",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/5-Meta-Mask-Setup",
    category: "Crypto Blockchain",
  },
  {
    id: "6",
    title: "6 Ethereum Account",
    drive: "https://youtu.be/U8IEcyhAH6E",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/6-Ethereum-Account",
    category: "Crypto Blockchain",
  },
  {
    id: "7",
    title: "7 Cara Mendapatkan Testnet Eth",
    drive: "https://youtu.be/9Md5o4KlFrc",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/7-Cara-Mendapatkan-Testnet-Eth",
    category: "Crypto Blockchain",
  },
  {
    id: "8",
    title: "8 Transaksi",
    drive: "https://youtu.be/ypkWfb0pwuo",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/8-Transaksi",
    category: "Crypto Blockchain",
  },
  {
    id: "9",
    title: "9 Kenapa ada waktu tunggu transaksi",
    drive: "https://youtu.be/a3aZWoh4Nfw",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/9-Kenapa-ada-waktu-tunggu-transaksi",
    category: "Crypto Blockchain",
  },
  {
    id: "10",
    title: "10 Basic Blockchain",
    drive: "https://youtu.be/XdBcQgknsAM",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/10-Basic-Blockchain",
    category: "Crypto Blockchain",
  },
  {
    id: "11",
    title: "11 Block Time",
    drive: "https://youtu.be/5kgKHrleZc0",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/11-Block-Time",
    category: "Crypto Blockchain",
  },
  {
    id: "12",
    title: "12 Smart Contract",
    drive: "https://youtu.be/jT8gl9_zk8k",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/12-Smart-Contract",
    category: "Crypto Blockchain",
  },
  {
    id: "13",
    title: "13 Solidity",
    drive: "https://youtu.be/nam-SdIchjY",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/13-Solidity",
    category: "Crypto Blockchain",
  },
  {
    id: "14",
    title: "14 Remix Interface",
    drive: "https://youtu.be/BADEUsmZtrc",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/14-Remix-Interface",
    category: "Crypto Blockchain",
  },
  {
    id: "15",
    title: "15 Contract Pertama Kita",
    drive: "https://youtu.be/3TLfvfalSRw",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/15-Contract-Pertama-Kita",
    category: "Crypto Blockchain",
  },
  {
    id: "16",
    title: "16 Struktur Contract",
    drive: "https://youtu.be/Fv_K_gEj2OY",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/16-Struktur-Contract",
    category: "Crypto Blockchain",
  },
  {
    id: "17",
    title: "17 Deklarasi Function",
    drive: "https://youtu.be/XkNP-eAe198",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/17-Deklarasi-Function",
    category: "Crypto Blockchain",
  },
  {
    id: "18",
    title: "18 Testing and Deploying Contract di Remix",
    drive: "https://youtu.be/ftwkBzAlWAw",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/18-Testing-and-Deploying-Contract-di-Remix",
    category: "Crypto Blockchain",
  },
  {
    id: "19",
    title: "19 Re deploy Smart Contract",
    drive: "https://youtu.be/UhRhZ-0y9AY",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/19-Re-deploy-Smart-Contract",
    category: "Crypto Blockchain",
  },
  {
    id: "20",
    title: "20 BTS Smart Contract Deployment",
    drive: "https://youtu.be/Y6fXqwOxrcA",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/20-BTS-Smart-Contract-Deployment",
    category: "Crypto Blockchain",
  },
  {
    id: "21",
    title: "21 Menjalankan Function in depth",
    drive: "https://youtu.be/NF3hDuxpr_A",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/21-Menjalankan-Function-in-depth",
    category: "Crypto Blockchain",
  },
  {
    id: "22",
    title: "22 Wei vs Ether",
    drive: "https://youtu.be/ksF7ZS1OCUo",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/22-Wei-vs-Ether",
    category: "Crypto Blockchain",
  },
  {
    id: "23",
    title: "23 Gas dan Transaksi",
    drive: "https://youtu.be/5T6XrSreAF0",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/23-Gas-dan-Transaksi",
    category: "Crypto Blockchain",
  },
  {
    id: "24",
    title: "24 Mnemonic Phrases",
    drive: "https://youtu.be/vkVV-8Nhfrw",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/24-Mnemonic-Phrases",
    category: "Crypto Blockchain",
  },
  {
    id: "25",
    title: "25 Setup Mengeluarkan Smart Contract dari Remix",
    drive: "https://youtu.be/JdCe8ug5A8s",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/25-Setup-Mengeluarkan-Smart-Contract-dari-Remix",
    category: "Crypto Blockchain",
  },  {
    id: "26",
    title: "26 Testing Architecture",
    drive: "https://youtu.be/0FW7n5GR7JA",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/26-Testing-Architecture",
    category: "Crypto Blockchain",
  },
  {
    id: "27",
    title: "27 Testing Modules",
    drive: "https://youtu.be/UZCmiQJjNbc",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/27-Testing-Modules",
    category: "Crypto Blockchain",
  },
  {
    id: "28",
    title: "28 Mocha Intro",
    drive: "https://youtu.be/VVpfIR_NTIE",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/28-Mocha-Intro",
    category: "Crypto Blockchain",
  },
  {
    id: "29",
    title: "29 Update Compiler untuk Solidity v0 8 19",
    drive: "https://youtu.be/8SDMLY9L1LM",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/29-Update-Compiler-untuk-Solidity-v0-8-19",
    category: "Crypto Blockchain",
  },
  {
    id: "30",
    title: "30 Flow Mocha Test",
    drive: "https://youtu.be/mGf3vZi4T1Q",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/30-Flow-Mocha-Test",
    category: "Crypto Blockchain",
  },
  {
    id: "31",
    title: "31 Ganache Accounts",
    drive: "https://youtu.be/-OXbvhsjypE",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/31-Ganache-Accounts",
    category: "Crypto Blockchain",
  },
  {
    id: "32",
    title: "32 Contract Deployment dengan Web3",
    drive: "https://youtu.be/GbusnSdus3s",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/32-Contract-Deployment-dengan-Web3",
    category: "Crypto Blockchain",
  },
  {
    id: "33",
    title: "33 Contract Assertion",
    drive: "https://youtu.be/fIyCH-3ZQRQ",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/33-Contract-Assertion",
    category: "Crypto Blockchain",
  },
  {
    id: "34",
    title: "34 Deployment dengan Infura",
    drive: "https://youtu.be/cNr7t_eG6N0",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/34-Deployment-dengan-Infura",
    category: "Crypto Blockchain",
  },
  {
    id: "35",
    title: "35 Wallet Provider Setup",
    drive: "https://youtu.be/ufEFYbOXm5k",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/35-Wallet-Provider-Setup",
    category: "Crypto Blockchain",
  },
  {
    id: "36",
    title: "36 Deploy ke Goerli",
    drive: "https://youtu.be/qF8RJMiV5P4",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/36-Deploy-ke-Goerli",
    category: "Crypto Blockchain",
  },
  {
    id: "37",
    title: "37 Deployed Contracts in Remix",
    drive: "https://youtu.be/_iTmpy8A_2Y",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/37-Deployed-Contracts-in-Remix",
    category: "Crypto Blockchain",
  },
  {
    id: "38",
    title: "38 Smart Contract Design",
    drive: "https://youtu.be/zDp1C4fkaqI",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/38-Smart-Contract-Design",
    category: "Crypto Blockchain",
  },
  {
    id: "39",
    title: "39 Solidity Basic Data Types",
    drive: "https://youtu.be/BjCHwbH0loI",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/39-Solidity-Basic-Data-Types",
    category: "Crypto Blockchain",
  },
  {
    id: "40",
    title: "40 Assign Manager Enter Lottery Flow",
    drive: "https://youtu.be/f0TcNTqR60M",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/40-Assign-Manager-Enter-Lottery-Flow",
    category: "Crypto Blockchain",
  },
  {
    id: "41",
    title: "41 Assign Players Testing",
    drive: "https://youtu.be/-_YBp_JsoyI",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/41-Assign-Players-Testing",
    category: "Crypto Blockchain",
  },
  {
    id: "42",
    title: "42 Validasi dengan Require",
    drive: "https://youtu.be/Pj4bwjiPw9w",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/42-Validasi-dengan-Require",
    category: "Crypto Blockchain",
  },
  {
    id: "43",
    title: "43 Memilih Pemenang Lottery",
    drive: "https://youtu.be/5dWAcYtyIq8",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/43-Memilih-Pemenang-Lottery",
    category: "Crypto Blockchain",
  },
  {
    id: "44",
    title: "44 Kirim Hadiah Reset Lottery",
    drive: "https://youtu.be/PS9_s_RXxPU",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/44-Kirim-Hadiah-Reset-Lottery",
    category: "Crypto Blockchain",
  },
  {
    id: "45",
    title: "45 Function Modifiers",
    drive: "https://youtu.be/GMkpLe9pjoM",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/45-Function-Modifiers",
    category: "Crypto Blockchain",
  },
  {
    id: "46",
    title: "46 Deploying to Sepolia Testnet plus Challenge",
    drive: "https://youtu.be/19lblhkNcME",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/46-Deploying-to-Sepolia-Testnet-plus-Challenge",
    category: "Crypto Blockchain",
  },
  {
    id: "47",
    title: "47 Apa itu ERC 20",
    drive: "https://youtu.be/AdymB8HlZzU",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/47-Apa-itu-ERC-20",
    category: "Crypto Blockchain",
  },
  {
    id: "48",
    title: "48 ERC20 Smart Contract",
    drive: "https://youtu.be/jI_D-k4cSMM",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/48-ERC20-Smart-Contract",
    category: "Crypto Blockchain",
  },
  {
    id: "49",
    title: "49 Add Liquidity Pool",
    drive: "https://youtu.be/EmTuZxt6yEs",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/49-Add-Liquidity-Pool",
    category: "Crypto Blockchain",
  },
  {
    id: "50",
    title: "50 Introduction to Oracles",
    drive: "https://youtu.be/8jR5naS1jFI",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/50-Introduction-to-Oracles",
    category: "Crypto Blockchain",
  },
  {
    id: "51",
    title: "51 The Oracle Problem Types of Oracles",
    drive: "https://youtu.be/9UGFXQJXoiY",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/51-The-Oracle-Problem-Types-of-Oracles",
    category: "Crypto Blockchain",
  },
  {
    id: "52",
    title: "52 Chainlink VRF LINK Faucet",
    drive: "https://youtu.be/cHSW1VNIVJY",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/52-Chainlink-VRF-LINK-Faucet",
    category: "Crypto Blockchain",
  },
  {
    id: "53",
    title: "53 Chainlink VRF Subscription Method",
    drive: "https://youtu.be/cuACagJ-gS0",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/53-Chainlink-VRF-Subscription-Method",
    category: "Crypto Blockchain",
  },
  {
    id: "54",
    title: "54 Importing Contract",
    drive: "https://youtu.be/kC_9XVXyRXI",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/54-Importing-Contract",
    category: "Crypto Blockchain",
  },
  {
    id: "55",
    title: "55 Hardhat Tutorial Compile Deploy Testing",
    drive: "https://youtu.be/gJzOIHxqbdc",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/55-Hardhat-Tutorial-Compile-Deploy-Testing",
    category: "Crypto Blockchain",
  },
  {
    id: "56",
    title: "56 Call Delegate",
    drive: "https://youtu.be/rSgJdHwGWRk",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/56 Call Delegate",
    category: "Crypto Blockchain",
  },
  {
    id: "57",
    title: "57 Jenis Unit",
    drive: "https://youtu.be/HntyZPywsqc",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/57 Jenis Unit",
    category: "Crypto Blockchain",
  },
  {
    id: "58",
    title: "58 Smart Contrack Dev",
    drive: "https://youtu.be/ogmfnKlFYaE",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/58 Smart Contrack Dev",
    category: "Crypto Blockchain",
  },
  {
    id: "59",
    title: "59 Delegate Call Attack",
    drive: "https://youtu.be/s3o3uDlHQOE",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/59 Delegate Call Attack",
    category: "Crypto Blockchain",
  },
  {
    id: "60",
    title: "60 Fallback Functions",
    drive: "https://youtu.be/uOj0X7dE1lE",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/60 Fallback Functions",
    category: "Crypto Blockchain",
  },
  {
    id: "61",
    title: "61 Gambaran Storage Slot Solidity",
    drive: "https://youtu.be/gBGGwmV5BmY",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/61 Gambaran Storage Slot Solidity",
    category: "Crypto Blockchain",
  },
  {
    id: "62",
    title: "Assignment 1 ToDo",
    drive: "https://youtu.be/OiOI4UmFpsY",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/62 Assignment 1 ToDo",
    category: "Crypto Blockchain",
  },
  {
    id: "63",
    title: "63 Intro to Algorithm and Data Types",
    drive: "https://youtu.be/DsmaI--YooY",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/63 Intro to Algorithm and Data Types",
    category: "Crypto Blockchain",
  },
  {
    id: "64",
    title: "64 Solidity and Protocol",
    drive: "https://youtu.be/5roSiKENE7o",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/64 Solidity and Protocol",
    category: "Crypto Blockchain",
  },
  {
    id: "65",
    title: "65 Verify Contract Whit Hardhat & Thirdweb",
    drive: "https://youtu.be/XOFIY9uqh8g",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/65 Verify Contract Whit Hardhat & Thirdweb",
    category: "Crypto Blockchain",
  },
  {
    id: "66",
    title: "66 Basic Uniswap V2",
    drive: "https://youtu.be/htjlM3xAI3U",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/66 Basic Uniswap V2",
    category: "Crypto Blockchain",
  },
  {
    id: "67",
    title: "67 ERC20 Tax Token",
    drive: "https://youtu.be/5ZTy0QYpLTw",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/67 ERC20 Tax Token",
    category: "Crypto Blockchain",
  },
  {
    id: "68",
    title: "68 Disperse App Batch Transfer",
    drive: "https://youtu.be/o5QpKy72tqk",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/68 Disperse App Batch Transfer",
    category: "Crypto Blockchain",
  },
  {
    id: "69",
    title: "69 Merkle-Airdrop",
    drive: "https://youtu.be/3s-vt0MYiMc",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/69 Merkle-Airdrop",
    category: "Crypto Blockchain",
  },
];
