export const Data = [
  {
    id: "1",
    title: "Limiting Belief",
    drive: "https://youtu.be/aEIEZKbCIyk",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/1-Limiting-Belief",
    category: "Mentalitas Anak Jalanan",
  },
  {
    id: "2",
    title: "Focus",
    drive: "https://youtu.be/GB1FfB8pzQQ",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/2-Focus",
    category: "Mentalitas Anak Jalanan",
  },
  {
    id: "3",
    title: "Decision Making",
    drive: "https://youtu.be/14D4SsgxNBY",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/3-Decision-Making",
    category: "Mentalitas Anak Jalanan",
  },
  {
    id: "4",
    title: "Kekayaan dan Pikiran",
    drive: "https://youtu.be/uh-RL5aa61Q",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/4-Kekayaan-dan-Pikiran",
    category: "Mentalitas Anak Jalanan",
  },
  {
    id: "5",
    title: "Introduction to Sales",
    drive: "https://youtu.be/TtdBzMbOuz0",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/5-Introduction-to-Sales",
    category: "Sales Fundamentals",
  },
  {
    id: "6",
    title: "The Psychology of Selling",
    drive: "https://youtu.be/YlhNxcrtE6A",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/6-The-Psychology-of-Selling",
    category: "Sales Fundamentals",
  },
  {
    id: "7",
    title: "Building a Rapport",
    drive: "https://youtu.be/gCPpauz6ecs",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/7-Building-a-Rapport",
    category: "Sales Fundamentals",
  },
  {
    id: "8",
    title: "Cara Jadi Sales Yang Terbaik",
    drive: "https://youtu.be/dcjra7DaJSY",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/8-Cara-Jadi-Sales-Yang-Terbaik",
    category: "Sales Fundamentals",
  },
  {
    id: "9",
    title: "Sales Mentality",
    drive: "https://youtu.be/5SDfYxdyiIQ",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/9-Sales-Mentality",
    category: "Sales Fundamentals",
  },
  {
    id: "10",
    title: "Breakdown Tipe Penjualan",
    drive: "https://youtu.be/RkU9y42LD54",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/10-Breakdown-Tipe-Penjualan",
    category: "Sales Fundamentals",
  },
  {
    id: "11",
    title: "Decision Making Flow",
    drive: "https://youtu.be/CbxYvr122eU",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/11-Decision-Making-Flow",
    category: "Sales Fundamentals",
  },
  {
    id: "12",
    title: "The Art of Storytelling",
    drive: "https://youtu.be/0NlLAx4n_bA",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/12-The-Art-of-Storytelling",
    category: "Sales Fundamentals",
  },
  {
    id: "13",
    title: "The Art of Persuasion",
    drive: "https://youtu.be/2IqvrB74OmU",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/13-The-Art-of-Persuasion",
    category: "Sales Fundamentals",
  },
  {
    id: "14",
    title: "Sales Funnel",
    drive: "https://youtu.be/YuEYVFr2Z_0",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/14-Sales-Funnel",
    category: "Sales Fundamentals",
  },
  {
    id: "15",
    title: "How to Follow Up",
    drive: "https://youtu.be/9PL4SZl1Mj4",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/15-How-to-Follow-Up",
    category: "Sales Fundamentals",
  },
  {
    id: "16",
    title: "Objection Handling",
    drive: "https://youtu.be/5SW3zwdZPsk",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/16-Objection-Handling",
    category: "Sales Fundamentals",
  }
];